modLoader="javafml"
loaderVersion="[47,)" # Forge 47.x = 1.20.1
license="All Rights Reserved"

[[mods]]
modId="everyns_wilds"
version="0.0.1"
displayName="Everyn's Wilds"
displayURL="https://expeditionaryrealmsstudios.com/nav/everyns_wilds"
authors="Expeditionary Realms Studios"
description='''
MMORPG mod for Everyn's Wilds.
'''

[[dependencies.everyns_wilds]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.everyns_wilds]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
